// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXbGWlOy2gaBi_m5o6kt9xWjk0nyg3Qe0',
    appId: '1:806186970988:web:5178c1a1b5d0c38bd00d49',
    messagingSenderId: '806186970988',
    projectId: 'ecowallet-fyp-app',
    authDomain: 'ecowallet-fyp-app.firebaseapp.com',
    storageBucket: 'ecowallet-fyp-app.firebasestorage.app',
    measurementId: 'G-NRPZRRV1RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFDbJMbIz06l9lyTL2Lf9VexTBDe8Vkk',
    appId: '1:806186970988:android:f91e9a6f5e9b2bf1d00d49',
    messagingSenderId: '806186970988',
    projectId: 'ecowallet-fyp-app',
    storageBucket: 'ecowallet-fyp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB5H814xUPUVhWDcoCaBZuJYOyrZ5nbMI',
    appId: '1:806186970988:ios:180421200041670fd00d49',
    messagingSenderId: '806186970988',
    projectId: 'ecowallet-fyp-app',
    storageBucket: 'ecowallet-fyp-app.firebasestorage.app',
    iosClientId: '806186970988-d14d2cvs6nqebdj10eu5f62cep0o2nn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonEmmisionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB5H814xUPUVhWDcoCaBZuJYOyrZ5nbMI',
    appId: '1:806186970988:ios:180421200041670fd00d49',
    messagingSenderId: '806186970988',
    projectId: 'ecowallet-fyp-app',
    storageBucket: 'ecowallet-fyp-app.firebasestorage.app',
    iosClientId: '806186970988-d14d2cvs6nqebdj10eu5f62cep0o2nn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonEmmisionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXbGWlOy2gaBi_m5o6kt9xWjk0nyg3Qe0',
    appId: '1:806186970988:web:8ff5c623295cf35fd00d49',
    messagingSenderId: '806186970988',
    projectId: 'ecowallet-fyp-app',
    authDomain: 'ecowallet-fyp-app.firebaseapp.com',
    storageBucket: 'ecowallet-fyp-app.firebasestorage.app',
    measurementId: 'G-2KS7J0RSF8',
  );

}